courseera.mail=lakshmihymavathichaturvedula@gmail.com
courseera.password=Hyma@2002
login.page=https://www.coursera.org/?authMode=login

chromedriver.path=C:\\Users\\hp\\OneDrive\\Desktop\\Selenium Web Driver\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe